# Compiles and Runs the program
OBJS = main.cpp

CC = g++

COMPILER_FLAGS = -Ofast

LINKER_FLAGS = -lSDL2

OBJ_NAME = program

all : $(OBJS)
	$(CC) $(OBJS) $(COMPILER_FLAGS) $(LINKER_FLAGS) -o $(OBJ_NAME) ; ./program

